export interface CountryOption {
  code: string
  name_en: string
  name_zh: string
}

export const POPULAR_CODES = new Set([
  'US', 'GB', 'CA', 'AU', 'DE', 'FR', 'JP', 'KR', 'BR', 'MX',
  'TW', 'TH', 'ID', 'VN', 'IN', 'PH', 'MY', 'SG', 'IT', 'ES',
])

export const ALL_COUNTRIES: CountryOption[] = [
  { code: 'AF', name_en: 'Afghanistan', name_zh: '阿富汗' },
  { code: 'AL', name_en: 'Albania', name_zh: '阿尔巴尼亚' },
  { code: 'DZ', name_en: 'Algeria', name_zh: '阿尔及利亚' },
  { code: 'AD', name_en: 'Andorra', name_zh: '安道尔' },
  { code: 'AO', name_en: 'Angola', name_zh: '安哥拉' },
  { code: 'AG', name_en: 'Antigua and Barbuda', name_zh: '安提瓜和巴布达' },
  { code: 'AR', name_en: 'Argentina', name_zh: '阿根廷' },
  { code: 'AM', name_en: 'Armenia', name_zh: '亚美尼亚' },
  { code: 'AU', name_en: 'Australia', name_zh: '澳大利亚' },
  { code: 'AT', name_en: 'Austria', name_zh: '奥地利' },
  { code: 'AZ', name_en: 'Azerbaijan', name_zh: '阿塞拜疆' },
  { code: 'BS', name_en: 'Bahamas', name_zh: '巴哈马' },
  { code: 'BH', name_en: 'Bahrain', name_zh: '巴林' },
  { code: 'BD', name_en: 'Bangladesh', name_zh: '孟加拉国' },
  { code: 'BB', name_en: 'Barbados', name_zh: '巴巴多斯' },
  { code: 'BY', name_en: 'Belarus', name_zh: '白俄罗斯' },
  { code: 'BE', name_en: 'Belgium', name_zh: '比利时' },
  { code: 'BZ', name_en: 'Belize', name_zh: '伯利兹' },
  { code: 'BJ', name_en: 'Benin', name_zh: '贝宁' },
  { code: 'BT', name_en: 'Bhutan', name_zh: '不丹' },
  { code: 'BO', name_en: 'Bolivia', name_zh: '玻利维亚' },
  { code: 'BA', name_en: 'Bosnia and Herzegovina', name_zh: '波黑' },
  { code: 'BW', name_en: 'Botswana', name_zh: '博茨瓦纳' },
  { code: 'BR', name_en: 'Brazil', name_zh: '巴西' },
  { code: 'BN', name_en: 'Brunei', name_zh: '文莱' },
  { code: 'BG', name_en: 'Bulgaria', name_zh: '保加利亚' },
  { code: 'BF', name_en: 'Burkina Faso', name_zh: '布基纳法索' },
  { code: 'BI', name_en: 'Burundi', name_zh: '布隆迪' },
  { code: 'KH', name_en: 'Cambodia', name_zh: '柬埔寨' },
  { code: 'CM', name_en: 'Cameroon', name_zh: '喀麦隆' },
  { code: 'CA', name_en: 'Canada', name_zh: '加拿大' },
  { code: 'CV', name_en: 'Cape Verde', name_zh: '佛得角' },
  { code: 'CF', name_en: 'Central African Republic', name_zh: '中非' },
  { code: 'TD', name_en: 'Chad', name_zh: '乍得' },
  { code: 'CL', name_en: 'Chile', name_zh: '智利' },
  { code: 'CN', name_en: 'China', name_zh: '中国' },
  { code: 'CO', name_en: 'Colombia', name_zh: '哥伦比亚' },
  { code: 'KM', name_en: 'Comoros', name_zh: '科摩罗' },
  { code: 'CG', name_en: 'Congo', name_zh: '刚果(布)' },
  { code: 'CD', name_en: 'Congo (DRC)', name_zh: '刚果(金)' },
  { code: 'CR', name_en: 'Costa Rica', name_zh: '哥斯达黎加' },
  { code: 'CI', name_en: 'Ivory Coast', name_zh: '科特迪瓦' },
  { code: 'HR', name_en: 'Croatia', name_zh: '克罗地亚' },
  { code: 'CU', name_en: 'Cuba', name_zh: '古巴' },
  { code: 'CY', name_en: 'Cyprus', name_zh: '塞浦路斯' },
  { code: 'CZ', name_en: 'Czech Republic', name_zh: '捷克' },
  { code: 'DK', name_en: 'Denmark', name_zh: '丹麦' },
  { code: 'DJ', name_en: 'Djibouti', name_zh: '吉布提' },
  { code: 'DM', name_en: 'Dominica', name_zh: '多米尼克' },
  { code: 'DO', name_en: 'Dominican Republic', name_zh: '多米尼加' },
  { code: 'EC', name_en: 'Ecuador', name_zh: '厄瓜多尔' },
  { code: 'EG', name_en: 'Egypt', name_zh: '埃及' },
  { code: 'SV', name_en: 'El Salvador', name_zh: '萨尔瓦多' },
  { code: 'GQ', name_en: 'Equatorial Guinea', name_zh: '赤道几内亚' },
  { code: 'ER', name_en: 'Eritrea', name_zh: '厄立特里亚' },
  { code: 'EE', name_en: 'Estonia', name_zh: '爱沙尼亚' },
  { code: 'SZ', name_en: 'Eswatini', name_zh: '斯威士兰' },
  { code: 'ET', name_en: 'Ethiopia', name_zh: '埃塞俄比亚' },
  { code: 'FJ', name_en: 'Fiji', name_zh: '斐济' },
  { code: 'FI', name_en: 'Finland', name_zh: '芬兰' },
  { code: 'FR', name_en: 'France', name_zh: '法国' },
  { code: 'GA', name_en: 'Gabon', name_zh: '加蓬' },
  { code: 'GM', name_en: 'Gambia', name_zh: '冈比亚' },
  { code: 'GE', name_en: 'Georgia', name_zh: '格鲁吉亚' },
  { code: 'DE', name_en: 'Germany', name_zh: '德国' },
  { code: 'GH', name_en: 'Ghana', name_zh: '加纳' },
  { code: 'GR', name_en: 'Greece', name_zh: '希腊' },
  { code: 'GD', name_en: 'Grenada', name_zh: '格林纳达' },
  { code: 'GT', name_en: 'Guatemala', name_zh: '危地马拉' },
  { code: 'GN', name_en: 'Guinea', name_zh: '几内亚' },
  { code: 'GW', name_en: 'Guinea-Bissau', name_zh: '几内亚比绍' },
  { code: 'GY', name_en: 'Guyana', name_zh: '圭亚那' },
  { code: 'HT', name_en: 'Haiti', name_zh: '海地' },
  { code: 'HN', name_en: 'Honduras', name_zh: '洪都拉斯' },
  { code: 'HK', name_en: 'Hong Kong', name_zh: '香港' },
  { code: 'HU', name_en: 'Hungary', name_zh: '匈牙利' },
  { code: 'IS', name_en: 'Iceland', name_zh: '冰岛' },
  { code: 'IN', name_en: 'India', name_zh: '印度' },
  { code: 'ID', name_en: 'Indonesia', name_zh: '印度尼西亚' },
  { code: 'IR', name_en: 'Iran', name_zh: '伊朗' },
  { code: 'IQ', name_en: 'Iraq', name_zh: '伊拉克' },
  { code: 'IE', name_en: 'Ireland', name_zh: '爱尔兰' },
  { code: 'IL', name_en: 'Israel', name_zh: '以色列' },
  { code: 'IT', name_en: 'Italy', name_zh: '意大利' },
  { code: 'JM', name_en: 'Jamaica', name_zh: '牙买加' },
  { code: 'JP', name_en: 'Japan', name_zh: '日本' },
  { code: 'JO', name_en: 'Jordan', name_zh: '约旦' },
  { code: 'KZ', name_en: 'Kazakhstan', name_zh: '哈萨克斯坦' },
  { code: 'KE', name_en: 'Kenya', name_zh: '肯尼亚' },
  { code: 'KI', name_en: 'Kiribati', name_zh: '基里巴斯' },
  { code: 'KP', name_en: 'North Korea', name_zh: '朝鲜' },
  { code: 'KR', name_en: 'South Korea', name_zh: '韩国' },
  { code: 'KW', name_en: 'Kuwait', name_zh: '科威特' },
  { code: 'KG', name_en: 'Kyrgyzstan', name_zh: '吉尔吉斯斯坦' },
  { code: 'LA', name_en: 'Laos', name_zh: '老挝' },
  { code: 'LV', name_en: 'Latvia', name_zh: '拉脱维亚' },
  { code: 'LB', name_en: 'Lebanon', name_zh: '黎巴嫩' },
  { code: 'LS', name_en: 'Lesotho', name_zh: '莱索托' },
  { code: 'LR', name_en: 'Liberia', name_zh: '利比里亚' },
  { code: 'LY', name_en: 'Libya', name_zh: '利比亚' },
  { code: 'LI', name_en: 'Liechtenstein', name_zh: '列支敦士登' },
  { code: 'LT', name_en: 'Lithuania', name_zh: '立陶宛' },
  { code: 'LU', name_en: 'Luxembourg', name_zh: '卢森堡' },
  { code: 'MO', name_en: 'Macao', name_zh: '澳门' },
  { code: 'MG', name_en: 'Madagascar', name_zh: '马达加斯加' },
  { code: 'MW', name_en: 'Malawi', name_zh: '马拉维' },
  { code: 'MY', name_en: 'Malaysia', name_zh: '马来西亚' },
  { code: 'MV', name_en: 'Maldives', name_zh: '马尔代夫' },
  { code: 'ML', name_en: 'Mali', name_zh: '马里' },
  { code: 'MT', name_en: 'Malta', name_zh: '马耳他' },
  { code: 'MR', name_en: 'Mauritania', name_zh: '毛里塔尼亚' },
  { code: 'MU', name_en: 'Mauritius', name_zh: '毛里求斯' },
  { code: 'MX', name_en: 'Mexico', name_zh: '墨西哥' },
  { code: 'MD', name_en: 'Moldova', name_zh: '摩尔多瓦' },
  { code: 'MC', name_en: 'Monaco', name_zh: '摩纳哥' },
  { code: 'MN', name_en: 'Mongolia', name_zh: '蒙古' },
  { code: 'ME', name_en: 'Montenegro', name_zh: '黑山' },
  { code: 'MA', name_en: 'Morocco', name_zh: '摩洛哥' },
  { code: 'MZ', name_en: 'Mozambique', name_zh: '莫桑比克' },
  { code: 'MM', name_en: 'Myanmar', name_zh: '缅甸' },
  { code: 'NA', name_en: 'Namibia', name_zh: '纳米比亚' },
  { code: 'NR', name_en: 'Nauru', name_zh: '瑙鲁' },
  { code: 'NP', name_en: 'Nepal', name_zh: '尼泊尔' },
  { code: 'NL', name_en: 'Netherlands', name_zh: '荷兰' },
  { code: 'NZ', name_en: 'New Zealand', name_zh: '新西兰' },
  { code: 'NI', name_en: 'Nicaragua', name_zh: '尼加拉瓜' },
  { code: 'NE', name_en: 'Niger', name_zh: '尼日尔' },
  { code: 'NG', name_en: 'Nigeria', name_zh: '尼日利亚' },
  { code: 'MK', name_en: 'North Macedonia', name_zh: '北马其顿' },
  { code: 'NO', name_en: 'Norway', name_zh: '挪威' },
  { code: 'OM', name_en: 'Oman', name_zh: '阿曼' },
  { code: 'PK', name_en: 'Pakistan', name_zh: '巴基斯坦' },
  { code: 'PA', name_en: 'Panama', name_zh: '巴拿马' },
  { code: 'PG', name_en: 'Papua New Guinea', name_zh: '巴布亚新几内亚' },
  { code: 'PY', name_en: 'Paraguay', name_zh: '巴拉圭' },
  { code: 'PE', name_en: 'Peru', name_zh: '秘鲁' },
  { code: 'PH', name_en: 'Philippines', name_zh: '菲律宾' },
  { code: 'PL', name_en: 'Poland', name_zh: '波兰' },
  { code: 'PT', name_en: 'Portugal', name_zh: '葡萄牙' },
  { code: 'QA', name_en: 'Qatar', name_zh: '卡塔尔' },
  { code: 'RO', name_en: 'Romania', name_zh: '罗马尼亚' },
  { code: 'RU', name_en: 'Russia', name_zh: '俄罗斯' },
  { code: 'RW', name_en: 'Rwanda', name_zh: '卢旺达' },
  { code: 'SA', name_en: 'Saudi Arabia', name_zh: '沙特阿拉伯' },
  { code: 'SN', name_en: 'Senegal', name_zh: '塞内加尔' },
  { code: 'RS', name_en: 'Serbia', name_zh: '塞尔维亚' },
  { code: 'SC', name_en: 'Seychelles', name_zh: '塞舌尔' },
  { code: 'SL', name_en: 'Sierra Leone', name_zh: '塞拉利昂' },
  { code: 'SG', name_en: 'Singapore', name_zh: '新加坡' },
  { code: 'SK', name_en: 'Slovakia', name_zh: '斯洛伐克' },
  { code: 'SI', name_en: 'Slovenia', name_zh: '斯洛文尼亚' },
  { code: 'SB', name_en: 'Solomon Islands', name_zh: '所罗门群岛' },
  { code: 'SO', name_en: 'Somalia', name_zh: '索马里' },
  { code: 'ZA', name_en: 'South Africa', name_zh: '南非' },
  { code: 'SS', name_en: 'South Sudan', name_zh: '南苏丹' },
  { code: 'ES', name_en: 'Spain', name_zh: '西班牙' },
  { code: 'LK', name_en: 'Sri Lanka', name_zh: '斯里兰卡' },
  { code: 'SD', name_en: 'Sudan', name_zh: '苏丹' },
  { code: 'SR', name_en: 'Suriname', name_zh: '苏里南' },
  { code: 'SE', name_en: 'Sweden', name_zh: '瑞典' },
  { code: 'CH', name_en: 'Switzerland', name_zh: '瑞士' },
  { code: 'SY', name_en: 'Syria', name_zh: '叙利亚' },
  { code: 'TW', name_en: 'Taiwan', name_zh: '台湾' },
  { code: 'TJ', name_en: 'Tajikistan', name_zh: '塔吉克斯坦' },
  { code: 'TZ', name_en: 'Tanzania', name_zh: '坦桑尼亚' },
  { code: 'TH', name_en: 'Thailand', name_zh: '泰国' },
  { code: 'TL', name_en: 'Timor-Leste', name_zh: '东帝汶' },
  { code: 'TG', name_en: 'Togo', name_zh: '多哥' },
  { code: 'TO', name_en: 'Tonga', name_zh: '汤加' },
  { code: 'TT', name_en: 'Trinidad and Tobago', name_zh: '特立尼达和多巴哥' },
  { code: 'TN', name_en: 'Tunisia', name_zh: '突尼斯' },
  { code: 'TR', name_en: 'Turkey', name_zh: '土耳其' },
  { code: 'TM', name_en: 'Turkmenistan', name_zh: '土库曼斯坦' },
  { code: 'TV', name_en: 'Tuvalu', name_zh: '图瓦卢' },
  { code: 'UG', name_en: 'Uganda', name_zh: '乌干达' },
  { code: 'UA', name_en: 'Ukraine', name_zh: '乌克兰' },
  { code: 'AE', name_en: 'United Arab Emirates', name_zh: '阿联酋' },
  { code: 'GB', name_en: 'United Kingdom', name_zh: '英国' },
  { code: 'US', name_en: 'United States', name_zh: '美国' },
  { code: 'UY', name_en: 'Uruguay', name_zh: '乌拉圭' },
  { code: 'UZ', name_en: 'Uzbekistan', name_zh: '乌兹别克斯坦' },
  { code: 'VU', name_en: 'Vanuatu', name_zh: '瓦努阿图' },
  { code: 'VE', name_en: 'Venezuela', name_zh: '委内瑞拉' },
  { code: 'VN', name_en: 'Vietnam', name_zh: '越南' },
  { code: 'YE', name_en: 'Yemen', name_zh: '也门' },
  { code: 'ZM', name_en: 'Zambia', name_zh: '赞比亚' },
  { code: 'ZW', name_en: 'Zimbabwe', name_zh: '津巴布韦' },
]
